### ISSUE TITLE
Error when inserting value

### ISSUE THREAD

**Issue by sandorvasas** [syncfusion/ej2-react-ui-components#10]
Getting
```
IndexSizeError: Failed to execute 'setStart' on 'Range': There is no child at offset 2.

and

IndexSizeError: Failed to execute 'setEnd' on 'Range': There is no child at offset 4.
```

when setting the `value` prop the `RichTextEditorComponent`.

What's the proper way to do this?

**Comment by PrinceOliver** [comment]
Hi @sandorvasas,

Greetings from Syncfusion support.

The proper way to set RTE value is using value property. During rendering time, you can directly provide it in the element and when setting dynamically you can access the property from the control’s instance.

`this.rteObj.value = 'The RTE value is changed dynamically';`
`this.rteObj.dataBind();`
 
We have attached a test sample for your reference, please find it in the following link: https://stackblitz.com/edit/react-wtzwz2-fuqusv

We have validated the error you reported, unfortunately we could not replicate the issue in our end. We have tried to set the value to the editor to replicate your scenario, using the following ways.

•	Loaded the content by default
•	Dynamically changed the value
•	Updated the content through template property
•	Insert the HTML into selected range using exec command

Kindly check the above test example as well as the steps and let us know where we have missed to replicate the issue. If possible, please share us a sample which replicate the issue or you can modify the above test example and revert it to us. This will help us isolate the cause of the issue and provide a prompt solution.

Regards,
Prince

**Comment by sandorvasas** [comment]
Thanks. Inserting with the `valueTemplate` prop apparently probably solved the problem. At least we haven't received range errors for a while now.

**Comment by rajendranr-5483** [comment]
Thanks @sandorvasas ,
