### ISSUE TITLE
google font link doesn't work

### ISSUE THREAD

**Issue by dryqiao** [syncfusion/ej2-react-ui-components#100]
Hi:
I saw code below in every material.css

`@import url("https://fonts.googleapis.com/css?family=Roboto:400,500");`

this link sometimes doesn't work, how can I remove it ?
Thanks

**Comment by GOKUL3897** [comment]
Hi @dryqiao,

Greetings from Syncfusion support,

We have prepared a small utility to resolve the reported issue at our end. Please follow the below steps to add our utility.

**Step 1**: Create a new js file and name it as **remove-robto.js**. Then add the following scripts to that file.

> varfs = require('fs');
> 
> varcontent = fs.readFileSync('./node_modules/@syncfusion/ej2-base/styles/material.css','utf-8');
> content =  content.replace('@import url(https://fonts.googleapis.com/css?family=Roboto:400,500);','');
> fs.writeFileSync('./node_modules/@syncfusion/ej2-base/styles/material.css',content);
> console.log('Roboto online reference removed');

**Step 2**: The following commands should be added to the scripts in the **package.json** file.

`
"postinstall": "node remove-robto.js"
`

**Step 3**: Now run the “**npm install**” command to install the dependent package.

**Step 4**: Run the “**npm run dev**” command to run the application in the browser.

Every time while installing the packages the Google Roboto font link will be removed automatically from the CSS file.

Please let us know if you need further assistance.

Regards,
Gokul

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 2 weeks. Closing for housekeeping purposes.
