### ISSUE TITLE
Error import tailwindcss scss with react-scripts@5.0.0

### ISSUE THREAD

**Issue by lorenzo3ds** [syncfusion/ej2-react-ui-components#104]
index.scss
```scss
@tailwind base;
@tailwind components;
@tailwind utilities;

@import "~@syncfusion/ej2-base/styles/tailwind";
@import "~@syncfusion/ej2-react-inputs/styles/tailwind";
```

Console error
```console
ERROR in ./src/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/index.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'type' of undefined
```

.env
```
SASS_PATH=./node_modules/@syncfusion
```

Package.json
```json
{
  "name": "hello-wrold",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@syncfusion/ej2-react-inputs": "^19.3.53",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.0.3",
    "@types/node": "^16.11.15",
    "@types/react": "^17.0.37",
    "@types/react-dom": "^17.0.11",
    "node-sass": "^7.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "typescript": "^4.5.4",
    "web-vitals": "^2.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "autoprefixer": "^10.4.0",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.7"
  }
}
```

**Comment by GOKUL3897** [comment]
Hi @lorenzo3ds,

We are unable to reproduce the reported issue. It seems that you have not included the SCSS file correctly in your project. We suggest you follow the below documentation steps to run the working project. For your reference, we have created a small project in the button component along with the tailwind theme.

Documentation: https://www.syncfusion.com/kb/12383/how-to-use-scss-in-syncfusion-react-component

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/ej2-react-grid1322336517

Please get back to us if you have any concerns.

Regards,
Gokul

**Comment by lorenzo3ds** [comment]
Hi and thanks for the reply.

Unfortunately, the example does not match the reported bug.
In fact, the Tailwind library has not been included, but only the scss have been included. This is a simple css import ...
The problem occurs when I include the tailwind scss of your packages with the tailwind installed
[Install Tailwind CSS with Create React App](https://tailwindcss.com/docs/guides/create-react-app)

The scss files have been included as documentation and everything is visible as reported in the bug.
I tried again with a new project and the problem remained.

I am waiting for a reply
Thank you

Regards,
Lorenzo

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 2 weeks. Closing for housekeeping purposes.
