### ISSUE TITLE
React 18.2 not rendering spreadsheet component

### ISSUE THREAD

**Issue by leerobert** [syncfusion/ej2-react-ui-components#112]
I'm able to properly render the spreadsheet in Next.js 12.2.5 / react 17.0.2 / react-dom 17.02 but when I bump react to 18.2 and react-dom to 18.2 with the same Next.js version I don't have the spreadsheet render at all.

Is react 18 not supported yet by the react components?

```
// basic `index.tsx` within pages/ for nextjs
import { SpreadsheetComponent } from "@syncfusion/ej2-react-spreadsheet";

export default () => {
  return (
    <SpreadsheetComponent allowOpen={true} openUrl="/api/spreadsheet/open" />
  );
};
```

**Comment by sangeetha-priya-M** [comment]
Hi Robert,


We have rendered the spreadsheet in react 18.2 version and the spreadsheet rendered properly in our end. Please find the link below.


Sample Link: https://stackblitz.com/edit/react-ts-zzjyje?file=index.tsx,package.json


Could you please check the above sample and replicate your issue in the above link and send back to us. Or else please share us the issue replicable sample. Based on that we will check and provide you a better solution quickly.


Regards,

Sangeetha M

**Comment by leerobert** [comment]
I figured it out. Strict mode breaks the rendering:

https://stackblitz.com/edit/nextjs-jj6w5b?file=next.config.js

If you disable the strict mode then it renders fine.

Perhaps just a note in the installation to be sure strict mode is not enabled for the component.

**Comment by syncsiva** [comment]
This issue has been closed due to no response from the original author. Please feel free to reopen, if you have more information that can help us investigate the issue further.
