### ISSUE TITLE
Paging not working when datasource {result, count} pair

### ISSUE THREAD

**Issue by suatbayir1** [syncfusion/ej2-react-ui-components#114]

**Comment by Pavithra15** [comment]
While using the “custom Binding” to the Grid with “result” and “count” pair, for every grid actions(such as Filter, Page, etc.,), I have triggered the dataStateChange event and, in that event arguments I have send the corresponding action details(like skip, take, filter field, value, sort direction, etc.,) based on that, you can perform the action in your service and return the data as a result and count object. Please refer to the below code example and documentation link for more information.

`export default class App extends React.Component<{}, {}> {
  .  .  .
  public dataStateChange(state: DataStateChangeEventArgs) {
    this.orderService.execute(state).then((gridData) => {
      if (this.grid) {
        this.grid.dataSource = gridData
      }
    });
  }
  public render() {
    return (
      <div className='control-pane'>
        <GridComponent dataSource={this.data} ref={g => this.grid = g} pageSettings={this.pageSettings}
          dataBound={this.renderComplete} dataStateChange={this.dataStateChange} allowPaging={true}>
          .  .  .
          <Inject services={[Page]} />
        </GridComponent>
      </div>)
  }
};
  };
`

[https://ej2.syncfusion.com/react/documentation/grid/data-binding/data-binding/#custom-binding](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fej2.syncfusion.com%2Freact%2Fdocumentation%2Fgrid%2Fdata-binding%2Fdata-binding%2F%23custom-binding&data=05%7C01%7Cpavithra.subramaniyam%40syncfusion.com%7C56700652a5a94d53659b08dadcfe93b0%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638065283224251325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NrkaNb1iG%2Bb0avhi7W8C5OYf1Shsepu3TjtwrhnTJ0M%3D&reserved=0)

**Comment by syncsiva** [comment]
This issue has not had any activity for 1 week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
