### ISSUE TITLE
schedule calendar DST issue in recurrent events

### ISSUE THREAD

**Issue by elehaf16** [syncfusion/ej2-react-ui-components#116]
There is a problem with recurrent events when they cross the DST (Daylight Saving Time). This error occurs when you create a recurrent event with a timezone different from your schedule timezone, and that timezone has no DST, like this one: (UTC +00:00) Reykjavik. 

I set the schedule timezone to (UTC 00:00 Canary Islands).

You can compare the results if you create this event in google calendar, and when you create with syncfusion. I attached some images to see the differences.

With google calendar:
![Captura de Pantalla 2022-12-16 a las 13 14 48](https://user-images.githubusercontent.com/20958835/208106404-87eea4fa-476b-4c7d-91c1-8df517bcbf91.png)

You can see that the event is shift one hour later because you are watching the schedule in my schedule timezone that has DST. (UTC 00:00 Canary Islands).

But in syncfusion the event is not shifted one hour. I attach the image: 

![Captura de Pantalla 2022-12-16 a las 13 23 02](https://user-images.githubusercontent.com/20958835/208107775-412ef8db-47cc-4788-abe4-e032ed6977af.png)

So If you are watching the schedule on your own local time that has DST, (in my case setting up the schedule to  UTC 00:00 Canary Islands)  and then you create a recurrent event with a timezone that don't have DST, it displays in a wrong hour when the DST is apply, that in this year was between 2022/03/26 and 2022/03/27.

**Comment by vijayravi161099** [comment]
Hi elehaf16,

The Schedule component events DST(Daylight Saving Time) works based on the system time zone. When the browser timezone is set to any DST timezone, the scheduler applies the DST timezone. If not, the scheduler will not apply DST to shift the timing in recurring appointments and will continue to display normal time. Additionally, we logged the feedback to control this behavior. The feature will be included in any of our upcoming releases. Track the status by using the below link.

[https://www.syncfusion.com/feedback/35974/need-to-provide-support-for-enable-disable-the-dst-through-api-in-schedule](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F35974%2Fneed-to-provide-support-for-enable-disable-the-dst-through-api-in-schedule&data=05%7C01%7Cvijay.ravi%40syncfusion.com%7C9a7668e99f984265d3bb08dae4fd50d3%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638074073931717799%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XcewLZ8SjYec0dA7G6xZOaKLRA9oOqnY1cCXuz7JgQg%3D&reserved=0)

Regards,
Vijay Ravi.

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. This feature can be tracked through below feedback link further,
https://www.syncfusion.com/feedback/35974/need-to-provide-support-for-enable-disable-the-dst-through-api-in-schedule
