### ISSUE TITLE
Scheduler not rendering quick popup correctly in React 18

### ISSUE THREAD

**Issue by S-Cardenas** [syncfusion/ej2-react-ui-components#117]
Usually, when you open the quick info window (quick popup) in the scheduler, the bottom of the window will align itself with the bottom of the calendar if need be. However, when upgrading to react 18 and the latest version of the syncfusion libraries (20.3.x), the quick info window is now going below the calendar (see the attached images below).

I've also attached two stackblitz examples, one with React 17 and one with React 18 so that you can see the behavior for yourself. Can you please fix this promptly as it is a huge hinderance to our users in production as the calendar is now much harder, on in some cases impossible, to use.

React 17 (aligns itself to the bottom of the calendar)
<img width="1725" alt="Screenshot 2022-12-19 at 4 44 16 PM" src="https://user-images.githubusercontent.com/14102289/208532690-151a2356-ed73-4fdc-ae12-ade36c7d6923.png">

React 18 (the window goes below the calendar)
<img width="1726" alt="Screenshot 2022-12-19 at 4 45 06 PM" src="https://user-images.githubusercontent.com/14102289/208532734-e6587ced-d933-4cf9-a81e-203f692aad4c.png">

[Stackblitz Example with React 17](https://stackblitz.com/edit/react-qzva2c?file=src/App.js)
[Stackblitz Example with React 18
](https://stackblitz.com/edit/react-aqmdhd?file=src/App.js)

**Comment by SwathiRavi14** [comment]
We have logged the issue “Quick info popup not rendering correctly in React 18” as a bug at our end and you can track the status in the below feedback.



Feedback :[https://www.syncfusion.com/feedback/39951/quick-info-popup-not-rendering-correctly-in-react-18](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F39951%2Fquick-info-popup-not-rendering-correctly-in-react-18&data=05%7C01%7Cswathi.ravi%40syncfusion.com%7Cfe9785e7afa54279223708dae3452b14%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638072183449227975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VamiTnSIHaIRibxDxIlLDP6onPy7vLf2R%2F7vAgeBdzE%3D&reserved=0)



Meanwhile, we suggest you resolve the issue by setting up the min-height value to the .e-quick-popup-wrapper CSS class as shown in the snippet below.

Sample: [https://stackblitz.com/edit/react-zmes5g?file=src%2Fstyle.css,src%2FApp.js](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackblitz.com%2Fedit%2Freact-zmes5g%3Ffile%3Dsrc%252Fstyle.css%2Csrc%252FApp.js&data=05%7C01%7Cswathi.ravi%40syncfusion.com%7Cfe9785e7afa54279223708dae3452b14%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638072183449227975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0N%2FYDl%2FiYtJb3XHcWoDbzVnQN9itxE12ms9Jv7Yqszg%3D&reserved=0)

[style.css]

.quick-info-template .e-quick-popup-wrapper {

  min-height: 210px;

}

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. Further, the reported bug can be tracked through below feedback link further,
https://www.syncfusion.com/feedback/39951/quick-info-popup-not-rendering-correctly-in-react-18
