### ISSUE TITLE
Wrong types for majorSlotTemplate in timeScale property

### ISSUE THREAD

**Issue by marc-wittwer** [syncfusion/ej2-react-ui-components#124]
Hi there
I wanted to set the majorSlotTemplate of timeScale property in my typescript react project.
However the type definition only allows to set majorSlotTemplate to a string

```
<ScheduleComponent
           cssClass='timeline-resource'
            ref={timelineRef}
            width='100%'
            timeScale={
              {
                interval: 60,
                slotCount: 4,
                majorSlotTemplate: 'ABCDEFGH',              // this only accepts a string value and no function
                enable: true,
               }
            }
         >
            <ResourcesDirective>
              <ResourceDirective
               ...
            </ResourcesDirective>
            <ViewsDirective>
              <ViewDirective
                option='TimelineWeek'
                eventTemplate={eventTemplate.bind(this)}
                resourceHeaderTemplate={resourceHeaderTemplate.bind(this)}
              />
            </ViewsDirective>
            <Inject services={[TimelineViews, Resize, DragAndDrop]} />
          </ScheduleComponent>
```

The types of TimeScaleModel need to be updated:

```
export interface TimeScaleModel {
    ...
    /**
     * The template option to be applied for major time slot. Here, the
     *  template accepts either the string or HTMLElement as template design and then the parsed design is displayed
     *  onto the time cells. The time details can be accessed within this template.
     *
     * @default null
     */
    majorSlotTemplate?: string;  // HERE should be the type Function or HTMLElement
}
```

What I tried:
- Setting the timeScale object **as any**

```
  function majorSlotTemplate(props: any) {
    const dateString = moment(props.date).format('HH');
    return <p style={{ fontSize: 12, paddingLeft: '1px' }}>{dateString}</p>;
  }

<ScheduleComponent
           cssClass='timeline-resource'
            ref={timelineRef}
            width='100%'
            timeScale={
              {
                interval: 60,
                slotCount: 4,
                majorSlotTemplate: majorSlotTemplate.bind(this),
                enable: true,
               } as any;
            }
/>
```

=> This worked, however, the page rerendered often and became really slow. A text input field on the same page had a 1 second input lag. The page became responsive again if I removed the majorSlotTemplate property.

- setting the timeScaleMajorSlotTemplate directly

```
...
timeScale={
              {
                interval: 60,
                slotCount: 4,
                enable: true,
               }}
timeScaleMajorSlotTemplate={majorSlotTemplate.bind(this)}
...
```
However, this did not work and the majorSlotTemplate did not change in appearance. 

This is my wanted styling and look of the timeline:
![image](https://user-images.githubusercontent.com/71826111/225440284-efc0dbf3-5cf4-4731-9c50-c6d79461d137.png)

More information in a forum post: https://www.syncfusion.com/forums/181035/wrong-types-for-timescale-property-in-typescript

Thanks for your help in advance.
Marc

**Comment by SwathiRavi14** [comment]
Hi Marc,

You can avoid the slow rendering of the component by adding the templates that you have used with the component in the statelessTemplates property, as shown in the below-shared snippet.

UG: https://ej2.syncfusion.com/react/documentation/common/template

[App.tsx]
`<ScheduleComponent statelissTemplates={['eventTemplate', 'majorSlotTemplate', 'resourceHeaderTemplate']}`

For template type-related queries, follow the below forum for further updates.

https://www.syncfusion.com/forums/181035/wrong-types-for-timescale-property-in-typescript

Regards,
Swathi Ravi

[ej2-react-schedule-statelessTemplates.zip](https://github.com/syncfusion/ej2-react-ui-components/files/10992863/ej2-react-schedule-statelessTemplates.zip)

**Comment by marc-wittwer** [comment]
Thanks a lot.

Adding the `statelessTemplate={['timeScale']}` seemed to improve performance :+1:

**Comment by gsumankumar** [comment]
This issue has been resolved. Please feel free to reopen if you have any further queries.
