### ISSUE TITLE
React Diagram Component

### ISSUE THREAD

**Issue by gordon-brown** [syncfusion/ej2-react-ui-components#130]
for link https://www.npmjs.com/package/@syncfusion/ej2-react-diagrams?activeTab=readme

this doesn't compile for me. I am just a react newbie, but I believe the import statement in app.tsx should be the below

import {
  DiagramComponent,
  NodeModel,
  ConnectorModel,
} from "@syncfusion/ej2-react-diagrams";

**Comment by sarathkumarvenkatesan** [comment]
Hi Gordon,

Thank you for your input! As a React newbie, your belief is indeed correct. The import statement in app.tsx should be updated to the following:


```
import {
  DiagramComponent,
  NodeModel,
  ConnectorModel,
} from '@syncfusion/ej2-react-diagrams';
```

This change has been recognized and merged into the repository. You can now update your local repository to get the latest changes and ensure the correct import is being used. If you have any more questions or need further assistance, feel free to ask. Happy coding!"

Regards,
Sarath

**Comment by gsumankumar** [comment]
We have resolved this issue and updated the repository. Therefore, we are closing this ticket for housekeeping purposes. Please do not hesitate to reopen it if you have any further queries.
