### ISSUE TITLE
Scheduler - collapse ResourceDirective by default

### ISSUE THREAD

**Issue by karlrez** [syncfusion/ej2-react-ui-components#132]
I am creating a similiar scheduler to [this example](https://ej2.syncfusion.com/react/demos/#/material/schedule/timeline-resource-grouping) 

I am looking to have the projects collapsed by default. I see the default value is "Expanded" but I cannot find what String is sopposed to go there for collapsed state.

Also, is it possible to add an onClick handler to this?

```
<ResourceDirective
   field="ProjectId"
   title="Choose Project"
   name="Projects"
   allowMultiple={false}
   dataSource={projectData}
   textField="text"
   idField="id"
   colorField="color"

   // these two props don't do anything 
   onClick = { () => console.log('on click') }
   expandedField="Collapsed"
/>
```

**Comment by Satheeshkumar0195** [comment]
Hi @karlrez, 

https://stackblitz.com/edit/react-nuauqd-d84yaf?file=index.js

**what String is supposed to go there for collapsed state.**

You can collapse all the resources by using the expandedField property, as shown in the below shared snippet.

Api: https://ej2.syncfusion.com/react/documentation/api/schedule/resources/#expandedfield

![image](https://github.com/syncfusion/ej2-react-ui-components/assets/44661161/bf08bacd-47ae-4f6c-bfbf-87ccbeb3e0e0)

**Also, is it possible to add an onClick handler to this?**

And you can add the onClick into the resource header using resourceHeaderTemplate, as shown in the below shared snippet.

Api: https://ej2.syncfusion.com/react/documentation/api/schedule#resourceheadertemplate

UG: https://ej2.syncfusion.com/react/documentation/schedule/resources#simple-resource-header-customization

![image](https://github.com/syncfusion/ej2-react-ui-components/assets/44661161/0ab66554-1074-4725-9c71-09d65adeb0ed)

**Comment by gsumankumar** [comment]
Hi @karlrez , We trust that the provided solution has successfully addressed the matter. Should you encounter any further issues or have any inquiries, please do not hesitate to reach out to us for further assistance.
