### ISSUE TITLE
RichTextEditor ToolBar this.tools are undefined when itemConfigs are configured.

### ISSUE THREAD

**Issue by ManjotSinghGill** [syncfusion/ej2-react-ui-components#139]
Package version: "@syncfusion/ej2-react-richtexteditor": "18.4.49",

### Toolbar Configuration

```
let toolbarSettings = {
  items: [
    'Undo',
    'Redo',
    'FontName',
    'FontSize',
    'Alignments',
    'BackgroundColor',
    'Bold',
    'Italic',
    'Underline',
    'StrikeThrough',
    'InsertCode',
    'UnorderedList',
    'OrderedList',
    'CreateLink',
    'Image',
    'SourceCode',
    'LowerCase',
    'UpperCase',
  ],
  itemConfigs: {
    undo: {
      icon: 'undo',
    },
    redo: {
      icon: 'redo',
    },
    justifyLeft: {
      icon: 'justifyLeft',
    },
    alignments: {
      icon: 'alignments',
    },
    bold: {
      icon: 'bold',
    },
    italic: {
      icon: 'italic',
    },
    underline: {
      icon: 'underline',
    },
  },
};
```

### Issue Description
I've been working on previously written code and we had an uncaught TypeError (see code below) when trying to toggle the Source View button in the toolbar.

```
toolbar.js:293 Uncaught TypeError: Cannot read properties of undefined (reading 'preview')
    at Toolbar.updateItem (toolbar.js:293:1)
    at Observer.notify (observer.js:99:1)
    at Component.notify (component.js:249:1)
    at ViewSource.sourceCode (view-source.js:105:1)
    at Observer.notify (observer.js:99:1)
    at Component.notify (component.js:249:1)
    at HtmlEditor.onToolbarClick (html-editor.js:279:1)
    at Observer.notify (observer.js:99:1)
    at Component.notify (component.js:249:1)
    at ToolbarAction.toolbarClick (toolbar-action.js:32:1)
```

The error is originating in the ToolBar.js Class's updateItem method line number 293.
ToolBar.tools is not an assigned property of the ToolBar class, causing this.tools to be undefined.

```
 Toolbar.prototype.updateItem = function (args) {
        var item = this.tools[args.updateItem.toLocaleLowerCase()];  --- this line (this.tools is undefined)
        var trgItem = this.tools[args.targetItem.toLocaleLowerCase()];
        var index = getTBarItemsIndex(getCollection(trgItem.subCommand), args.baseToolbar.toolbarObj.items)[0];
        if (!isNOU(index)) {
            var prefixId = this.parent.inlineMode.enable ? '_quick_' : '_toolbar_';
            args.baseToolbar.toolbarObj.items[index].id = this.parent.getID() + prefixId + item.id;
            args.baseToolbar.toolbarObj.items[index].prefixIcon = item.icon;
            args.baseToolbar.toolbarObj.items[index].tooltipText = item.tooltip;
            args.baseToolbar.toolbarObj.items[index].subCommand = item.subCommand;
            args.baseToolbar.toolbarObj.dataBind();
        }
        else {
            this.addTBarItem(args, 0);
        }
    };
```

All the other options work fine, the issue only arises in the case of the source view.
However, if I were to remove the itemsConfigs from the toolbar settings everything would work fine.

I went through the [Toolbar settings documentation](https://ej2.syncfusion.com/react/documentation/api/rich-text-editor/#toolbarsettings) but could not find anything useful, if this issue has been solved in newer versions please do let me know.

**Comment by VinithaJeyakumar** [comment]
Hi  ManjotSinghGill,


We have considered the reported issue "**Script error throws when clicking preview toolbar while using itemConfigs with ToolbarSettings in RichTextEdit** " as a bug from our end and the fix for the issue will be included with our upcoming patch release on 31st   October 2023.

Now you can track the status of the reported issue through the feedback below,
https://www.syncfusion.com/feedback/47753/script-error-throws-when-clicking-preview-toolbar-while-using-itemconfigs-with

**Disclaimer**: “Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.”

Regards,
Vinitha

**Comment by gsumankumar** [comment]
For housekeeping purposes, we are closing this ticket. You can monitor the status and progress of the reported bug by clicking on the feedback link below.
https://www.syncfusion.com/feedback/47753/script-error-throws-when-clicking-preview-toolbar-while-using-itemconfigs-with
