### ISSUE TITLE
Using font awesome in toolbar ItemDirective doesn't work.

### ISSUE THREAD

**Issue by Sven65** [syncfusion/ej2-react-ui-components#21]
Using `<ItemDirective prefixIcon='fas fa-cut' tooltipText='Cut' text='Cut' overflow='Show'/>`, the icon doesn't render, but instead shows a box for when the glyph isn't found.

Removing `@import '~@syncfusion/ej2-react-diagrams/styles/bootstrap.css';` from the CSS, it seems to work.

Similarly, using an `<i className='fas fa-cut' />` outside of the toolbar and item directive it works as intended.

**Comment by sellakumark** [comment]
Dear Customer,

Kindly try referring the refer the font awesome CSS below the Syncfusion CSS as shown.
https://stackblitz.com/edit/react-dsudq4-d2ptze?file=index.html 

<link href="https://cdn.syncfusion.com/ej2/material.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 

Regards,
Karthi

**Comment by Sven65** [comment]
Hi, the problem with this approach is that I'm loading your css through an `App.css` file, and the font-awesome through the `index.html` entrypoint, and I don't see the reason for changing the approach.

**Comment by Sven65** [comment]
Update: After some testing, it would seem that it works with font-awesome 4 but not font-awesome 5.

**Comment by rajendranr-5483** [comment]
@Sven65 ,

Sorry to missed the follow-up with you.

We close this thread now. Reopen it if you have any requirement still.
