### ISSUE TITLE
Bug on monthly event (days 29, 30 and 31)

### ISSUE THREAD

**Issue by gtaylor44** [syncfusion/ej2-react-ui-components#24]
If you setup a new event with a recurrence rule of:

Monthly
Repeat every = 1 month
Repeat on day = 31

There is an alert:
"Some months have fewer than the selected date. For these months, the occurrence will fall on the last date of the month."

Click OK to acknowledge this alert.

When event is saved, you will notice that days where there is less than 31 days, there is no event.

Expected behaviour:

If there are more days, then the event should fall on the last date of the month as explained in alert.

Verified this does not work on official demo site:
https://ej2.syncfusion.com/react/demos/#/material/schedule/default

**Comment by sellakumark** [comment]
Dear Customer,

Syncfusion greetings.

Currently month recurrence events are rendering correctly as per Google standard but with unwanted alert window. We confirm it as defect and the fix will be included in our JS2 weekly release on August 06, 2019.  

Regards,
Karthi

**Comment by gtaylor44** [comment]
Just done a test on Google Calendar. You're right, Google doesn't show an alert and does not create an event when days in month is less than 31.

**Comment by sellakumark** [comment]
Dear Customer,

Fix is included in v17.2.40 and kindly refer the below release notes (#243422).
https://ej2.syncfusion.com/javascript/documentation/release-notes/17.2.40/#schedule

Regards,
Karthi

**Comment by gtaylor44** [comment]
Verified the fix. Thanks.
