### ISSUE TITLE
TextBox autoComplete={'off'} not working

### ISSUE THREAD

**Issue by fsjobeck** [syncfusion/ej2-react-ui-components#25]
Currently it seems we're unable to turn off the auto complete feature for input fields that's built into chrome when using TextBox Component.
There doesn't seem to be any `autoComplete={'off'}` for TextBoxComponents that we can use, React should default to `autoComplete={}` when rendering JSX components. This seems to be missing. 
Examples below, where TextBoxComponent will still proc the auto complete from Chrome while the input field will not:

`<TextBoxComponent type={'text'} autoComplete={'off'}/>`

`<input autoComplete={'off'}/>`

**Comment by Gopigovin** [comment]
Hi Fredrik Sjobeck, 
 
Good day to you. 
 
We have checked your requirement for autocomplete property to set input element. We have provided htmlAttributes property for this case, you can use this property to specify the disabled, autocomplete etc., to the element. We have prepared sample based on your requirement. Please find the sample and code snippet for your reference.  

```
export class Textbox extends SampleBase { 
            constructor() { 
                super(...arguments); 
                this.htmlattr = { "autoComplete": "off" } 
            } 
            render() { 
                return (<div id="multichecbox" className='control-pane'> 
                    <div className='control-section col-lg-8'> 
                        <div id="multigroup" className="control-styles"> 
                            <TextBoxComponent placeholder="First Name" floatLabelType="Auto" htmlAttributes={this.htmlattr} /> 
                        </div> 
                    </div> 
                </div>); 
            } 
        } 
```
Sample Link: https://stackblitz.com/edit/react-jag9dw?file=index.js  
 
API Link: https://ej2.syncfusion.com/react/documentation/api/textbox/#htmlattributes 
 
Please let us know, if you have any concern on this. 
 
Regards,
Gopi G.

**Comment by fsjobeck** [comment]
Hey!
Thanks for the quick reply!
While the suggestion might work, I think it's a poor implementation and causes massive code clutter. It's also error prone and make reading and debugging code much harder, especially in larger code bases.

I can use the suggested way of doing it as a temporary fix, but this should honestly be properly revised :)

It's a suboptimal solution to the issue, as autoComplete is a commonly used attribute and not having it standardized in JSX syntax and following the basic principle feels off.

**If I may suggest;**
The following, common attributes, should be standardized in your component library for applicable types:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes_common_to_all_input_types

Syntax should follow:
https://reactjs.org/docs/dom-elements.html

For attributes **not** listed as common from the HTML5 standard the above suggested method is sensible. For commonly listed attributes in the standard it's not.

Best regards
Fredrik

**Comment by BerlyChristopher** [comment]
Hi Fsjobeck,

We have considered the requested requirement as a feature at our end and this support will be included in our upcoming **Volume 3 Release** expected to be rolled out at end of September 2019. We appreciate your patience until then. 

You can track the status of the requested feature from the below feedback link.

**Feedback Link**: https://www.syncfusion.com/feedback/8221/need-to-provide-autocomplete-api-support-for-textbox-component 

Task ID: https://syncfusion.atlassian.net/browse/EJ2-30458?oldIssueView=true 

We suggest you to use the provided workaround solution in the previous update until the feature has been included. 

Regards,
Berly B.C

**Comment by BerlyChristopher** [comment]
Hi Fsjobeck,

We are glad to announce that our **Essential Studio Volume 3, 2019 release (v17.3.0.14)** is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/148058/essential-studio-2019-volume-3-release-v17-3-0-14-is-available-for-download  

We have included the support for the reported issue “**Need to provide autocomplete API support for TextBox component**” in this release. So, we suggest you upgrade our Syncfusion packages to our latest version to resolve this issue in your end. We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Please find the sample and release notes details from the below link.

**Sample Link**: https://stackblitz.com/edit/angular-k5ytx6-cdwmm4?file=app.component.html

**Release notes**: https://ej2.syncfusion.com/documentation/release-notes/17.3.14/#textbox

Regards,
Berly B.C
