### ISSUE TITLE
TabItemDirective doesn't update content.

### ISSUE THREAD

**Issue by Sven65** [syncfusion/ej2-react-ui-components#30]
See the title for the issue and see https://stackblitz.com/edit/react-nf7zqn?file=index.js for an example.

As this issue has manifested itself many times before in different components, I'm starting to think that this is an issue in all of your components that are using this system of content rendering, and that you should look into that in order to stop these bugs from being in your entire package.

The entire point of using React in the first place is to stop having to write code that sets the content from another function other than the component itself, and have content be able to get changed without having each component as a `ref`, and the way you're doing this is overall a very bad practice for React.

**Comment by sellakumark** [comment]
Dear Customer, 

The provided sample is similar to https://github.com/syncfusion/ej2-react-ui-components/issues/27 and kindly try our sample and let us know for further assistance.

Regards,
Karthi

**Comment by rajendranr-5483** [comment]
@Sven65 ,

We are closing thread #30 and #27 due to long pending.

If you have any concerns, please reopen it.
