### ISSUE TITLE
TabComponent using router

### ISSUE THREAD

**Issue by amerkoleci** [syncfusion/ej2-react-ui-components#33]
Hi,

I would like to know if its possible to use react-router to set as content in TabItemDirective?
My application need to dynamically add/remove tab pages with different react component, any thought?

Does the DOM get updated when switching between tabs? What I mean does it render only the content being showed?

Thanks,
Amer

**Comment by vinithadevi** [comment]
DearCustomer,

Syncfusion Greetings.

We have prepared sample based on your requirement and same can be available in below link.

https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample472985433 

Kindly try the sample and Please let us know if you need any further assistance on this.  

Regards,
M.Vinitha devi

**Comment by rajendranr-5483** [comment]
@amerkoleci ,

We are closing this thread now due to long pending. Please reopen this thread if you have any other concerns or requirements.
