### ISSUE TITLE
DocumentEditorContainerComponent: text rendered displaced

### ISSUE THREAD

**Issue by hbj** [syncfusion/ej2-react-ui-components#34]
After updating `@syncfusion/ej2-react-documenteditor` from v16.4.54 to v17.2.51 we are experiencing an issue where the text in the editor is displayed displaced vertically. Cursor and selection highlight are displayed in the right places but text is displayed below its correct position by about 100 pixels.

For images the behaviour is a bit strange. If an image is by its own in a line, it's displayed in the correct place but the cursor is positioned displaced above it, but if there is text on the same line then it's displayed displaced with the text as described above.

Any idea what can cause this behaviour?

Screenshots:

Displaced text, cursor in correct position:
<img width="1441" alt="Screenshot 2019-09-12 12 45 54" src="https://user-images.githubusercontent.com/1281693/64781882-ced02b00-d55b-11e9-809a-e8d5573aea6e.png">

Displaced text, selection in correct position:
<img width="1441" alt="Screenshot 2019-09-12 12 46 08" src="https://user-images.githubusercontent.com/1281693/64781917-e3142800-d55b-11e9-82ba-99b34fcbf7ab.png">

Image with text, displaced and cursor in correct position:
<img width="1441" alt="Screenshot 2019-09-12 12 47 08" src="https://user-images.githubusercontent.com/1281693/64781944-f4f5cb00-d55b-11e9-8198-5aa0986f8341.png">

Image alone in line, correct position and cursor displaced:
<img width="1441" alt="Screenshot 2019-09-12 12 47 31" src="https://user-images.githubusercontent.com/1281693/64781993-1787e400-d55c-11e9-9903-4f547209423b.png">

**Comment by Suriya-Murugan** [comment]
Hi Hbj, 

We have tried to reproduce the reported issue in our latest source. The cursor and text position are proper. 
Please check the same in below sample. 
https://stackblitz.com/edit/react-duf6q8?file=index.js 
 
Can you please share the video illustration to reproduce the reported issue? so that we can investigate further and provide you solution at earliest. 
 
Regards, 
Suriya M.

**Comment by hbj** [comment]
Hi @Suriya-Murugan, I have upgraded to the latest version, v17.3.19, to create the video, but it seems that the issue has been fixed, so I will close this ticket for now. Thanks for your help.
