### ISSUE TITLE
layout issue in next js production build

### ISSUE THREAD

**Issue by skptricks** [syncfusion/ej2-react-ui-components#37]
toolbar layout is not getting displayed in left to right order.  please refer the below screenshot :

![image](https://user-images.githubusercontent.com/8350199/66860749-61c11280-efab-11e9-8b44-31e0251b35da.png)

**Comment by vinithadevi** [comment]
Dear customer,

We suspect that you missed to add the styles in your demo which could be a cause. Please refer below UG and sample. 

https://ej2.syncfusion.com/react/documentation/toolbar/getting-started/#adding-css-reference

https://stackblitz.com/edit/react-dhtp59?file=index.html 

Note: If you use react with javascript, please add below CSS link in index.html to load toolbar related styles.

    <link href="https://cdn.syncfusion.com/ej2/material.css" rel="stylesheet">

Regards,
M.Vinithadevi

**Comment by rajendranr-5483** [comment]
Hi @skptricks ,

We are closing this thread now due to long pending. Please reopen this thread if you have any other concerns or requirements.
