### ISSUE TITLE
Cannot read property 'headerDistance' of undefined when clicking in the header

### ISSUE THREAD

**Issue by antoineCMI** [syncfusion/ej2-react-ui-components#38]
In the DocumentEditorComponent, when a click in the header of my document I got this error in my console  : 

![image](https://user-images.githubusercontent.com/30807325/67598722-48069480-f73c-11e9-862e-2069dc2e8b6a.png)

The code :

![image](https://user-images.githubusercontent.com/30807325/67598837-91ef7a80-f73c-11e9-8526-be8d1c409d75.png)

I think the code should be : 

`
this.headerFromTop.value = this.documentEditor.selection.sectionFormat.headerDistance;
 this.footerFromTop.value = this.documentEditor.selection.sectionFormat.footerDistance;
`

My version of syncfusion/ej2-react-documenteditor is 17.3.19.

**Comment by Suriya-Murugan** [comment]
this.headerFromTop.value =   this.documentEditor.selection.sectionFormat.headerDistance;   this.footerFromTop.value =   this.documentEditor.selection.sectionFormat.footerDistance;
--

**Comment by Suriya-Murugan** [comment]
Hi Antonine,


Yes, we have to access header and footer distance value like below:
`this.headerFromTop.value = this.documentEditor.selection.sectionFormat.headerDistance; this.footerFromTop.value = this.documentEditor.selection.sectionFormat.footerDistance;`

We can reproduce the reported issue. We have fixed the issue and include in our upcoming EJ2 patch release which is scheduled on October 31,2019.
 

Regards,
Suriya M.
