### ISSUE TITLE
Error TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by usman-maktoob** [syncfusion/ej2-react-ui-components#39]

**Comment by Mydeen-SN** [comment]
Hi @usman-maktoob 

Your shared information is not sufficient to identify the extract issue in our end. We need more information to reproduce the issue. So, could you please share the below details to us. It will be helpful for us to focus on a specific area and assist you at the earliest. 

1.	Provide us the stack trace details of the error report. 
2.	If the issue occurs in any specific component, then provide us the component list 
3.	If possible, share us the replication procedure, sample code snippet with more details

**Comment by ajithr** [comment]
Hi @usman-maktoob 

We are marking this thread as closed. Please reopen if you need any further assistance with this.

Regards,
Ajith R
