### ISSUE TITLE
Schedule Component bug on monthly event (infinite loop)

### ISSUE THREAD

**Issue by elehaf16** [syncfusion/ej2-react-ui-components#42]
If you setup a new event with a recurrence rule of:

startDate: 2/28/18  (any february date)
endDate: 2/28/18 (any february date)

Repeat: Monthly
Repeat every: 12 Months
Repeat On Day: 31

End: any value

![Captura de pantalla 2020-01-31 a las 0 53 24](https://user-images.githubusercontent.com/20958835/73503817-34b33700-43c5-11ea-9a45-2fc89ca1252d.png)

the component crash in an infinite loop. 

I know that what the user is asking is not possible, but I think that a validation could be done to not let the app crash.

the same issue occur with this configuration:

![Captura de pantalla 2020-01-31 a las 1 29 59](https://user-images.githubusercontent.com/20958835/73505134-85c52a00-43c9-11ea-8075-867b6a4db39b.png)

The counter variable never get update because the recurrence option never happens

I think that a solution could be to display only the days that are allowed in the month on the BYMONTHDAY field. I mean, If the user choose a startDate on February only display from 1 to 29th or if the user choose a date from April only display from 1 to 30th.
Or another solution could be to put the field BYMONTHDAY readonly and chose the day that the user select from the startDate field.
Google Calendar implements the second solution ...

**Comment by sellakumark** [comment]
Dear Customer,

Greetings from Syncfusion Support.

We could able to reproduce the issue that you have reported. We had logged the defect report at our end and fix will be included in our JS2 weekly release on February 12, 2020. We will ensure the fix and provide further details on February 13, 2020. Kindly be patience until then.      
https://www.syncfusion.com/feedback/11729/schedule-component-bug-on-monthly-event-infinite-loop

Regards,
Sellakumar K

**Comment by VengateshManiraj** [comment]
Dear Customer, 

Thanks for your patience.  

We have fixed the reported issue and it has reflected in our v17.4.50 package version. You can get it by upgrading your package version to v17.4.50.   

https://ej2.syncfusion.com/angular/documentation/release-notes/index/#schedule 

Kindly let us know if you need further assistance. 

Regards, 
Vengatesh

**Comment by elehaf16** [comment]
Hi, I have upgraded to the latest version, and it seems that the issue has been fixed, so I'll close this ticket. 

I'd like to add that a validation must be made, otherwise the event is stored in the database, even if it's not visualized in the scheduler.

Thanks for your help.
