### ISSUE TITLE
Webpack fails becouse Unfinished comment in ej2-richtexteditor/src/rich-text-editor/base/interface.js

### ISSUE THREAD

**Issue by rosenangelov** [syncfusion/ej2-react-ui-components#43]
In the last version of richtexteditor 17.4.47 (https://registry.npmjs.org/@syncfusion/ej2-richtexteditor/-/ej2-richtexteditor-17.4.47.tgz) the file ej2-richtexteditor/src/rich-text-editor/base/interface.js have unfinished comment
![image](https://user-images.githubusercontent.com/968684/73864419-e1683b00-4841-11ea-80ab-2dc5c2ebdc01.png)

and because if this webpack fails:
![image](https://user-images.githubusercontent.com/968684/73864496-0d83bc00-4842-11ea-84d5-4365d7c21bd2.png)

When i remove the comment /** - webpack is compiling fine.

in the previous version the code was like this:
![image](https://user-images.githubusercontent.com/968684/73864768-7c611500-4842-11ea-98af-e130b4dcff98.png)

**Comment by ppisecky** [comment]
Same issue in Vue.

**Comment by Indrajith-Sync** [comment]
Hi @ppisecky / @rosenangelov,

We regret for the inconvenience caused,

We have resolved the issue with the RichTextEditor packages and the fix is now available with the release version **17.4.48**. 

Can you please upgrade your package to this version to resolve the issue from your end ?

Regards,
Indrajith

**Comment by ppisecky** [comment]
@Indrajith-Sync I don't think version 17.4.48 has been released yet. At least not for the Vue port of `@syncfusion/ej2-vue-gantt@^17.4.48` (according to npm which cant resolve `.48` - the latest github releases only mention `.47` for both React and Vue so I can't verify.

**Comment by rosenangelov** [comment]
Hi @Indrajith-Sync,
thank you for the fast bug solving. Working fine now.
Regards,
Rosen

**Comment by rajendranr-5483** [comment]
Hi @rosenangelov ,

Thanks for your update.
