### ISSUE TITLE
Feature: Swap DayScale / TimeScale in Scheduler component 

### ISSUE THREAD

**Issue by vtrphan** [syncfusion/ej2-react-ui-components#46]
Hello,
is it possible to swap the Day- /TimeScale in the Scheduler component, i.e. the TimeScale will be horizontal and DateScale will be vertical. It is like another view in which the appointments for a date are now arranged horizontally instead of vertically.

Also, is it possible to multi-select and multi-drag-drop appointments, and "zoom" into the timeslot by mousewheel, i.e. the  TimeScale will be displayed more fine granular (zoom down to 5 minute interval).

My customer absolutely wants those features.

**Comment by Ravikumar-Venkatesan-M** [comment]
Dear Customer,

Greetings from Syncfusion support.

We let you know that your query has been addressed in the below community forum. Kindly refer the below link and get back to us if you would require any further assistance. 

https://www.syncfusion.com/forums/152159/swap-dayscale-timescale-in-scheduler-component

Regards,
Ravikumar Venkatesan

**Comment by rajendranr-5483** [comment]
@vtrphan ,

Sorry for the delay to get back to you.

We are closing this thread now. Please reopen this thread if you have any other concerns or requirements.
