### ISSUE TITLE
Possible Bug Between <MultiSelectComponent> and <ScheduleComponent>

### ISSUE THREAD

**Issue by GregMayes** [syncfusion/ej2-react-ui-components#48]
**Affected versions:**
React: 16.13.1
@syncfusion/ej2-react-dropdowns: 17.4.51
@syncfusion/ej2-react-navigations: 17.4.55

**Background**
We have an instance of the \<ScheduleComponent\> component, which we pass an editorTemplate prop to. The passed JSX contains a \<MultiSelectComponent\> component, which is a user selector.

If the editor window modal is opened without an initial value set to the user selector, and then you click the 'Save' button, it correctly fires the actionBegin event as expected.

**Recreating Possible Bug**
1. Open the editor window modal
2. Select a user in the \<MultiSelectComponent\>
3. Clear your selection
4. Click the 'Save' button on the modal

You should see that it closes the modal without firing the actionBegin event.

It's also worth noting that if you were to select 2 users, clear one and then submit it will correctly fire the actionBegin event. This issue only seems to occur when you fully clear it.

**Comment by VengateshManiraj** [comment]
Hi GreyMayes,

Greetings from Syncfusion Support.

We have validated your reported problem that “actionBegin event is not triggered when submit save the event after clear all the selected items from MultiSelect” but unfortunately we are not able to reproduce the issue. For your reference, we have prepared a sample and it can be available in the below link.

Sample: https://stackblitz.com/edit/react-mdpgms-rdmbm6?file=index.js

_We are not having the package @syncfusion/ej2-react-dropdowns in the version of v17.4.51. So we have ensured your reported issue in our latest package version. Please refer the package details in below,
**@syncfusion/ej2-react-dropdowns: 18.1.45
@syncfusion/ej2-react-schedule: 18.1.45**_

Kindly check the above sample and please get back to us if you would require any further assistance. 

Regards,
Vengatesh

**Comment by GregMayes** [comment]
Hello Vengatesh,

It turns out that the issue was due to the MultiSelect's name clashing. If I change it to something other than UserId, then it works. My rough guess is that it's clashing with a ResourceDirective that has a field of UserId defined.

Many thanks,

Greg
