### ISSUE TITLE
Grid component updates when state changes.

### ISSUE THREAD

**Issue by Sven65** [syncfusion/ej2-react-ui-components#5]
Do you not keep an internal reference in the component to the data being passed down?

Selecting a row in the grid and using the `rowSelected` and `rowDeselected` to update the state in my component refreshes the data list and de-selects everything and removes my headers.

The hell are y'all doing?

**Comment by Pavithra15** [comment]
Hi @Sven65 ,

We can able to reproduce the reported issue “Selection is not maintained when using rowselected and rowdeselected event” and logged a defect report for the same. This fix will be available in our upcoming release which will be rolled out by mid of February 2019.

And regarding removal of headers query, we could not reproduce the issue at our end. If you are facing the problem, please share the following details to provide you with a better solution as early as possible.
1.	Share the full Grid code example.
2.	Share the exact scenario/proper replication procedure.

Regards,
Pavithra S.

**Comment by essentialjs2** [comment]
We are able to reproduce the reported issue “**_Selection is not maintained when using rowselected and rowdeselected event_**” and logged a defect report for the same. This fix will be available in upcoming **February 13, 2019** patch release.

And regarding removal of headers query, We could not reproduce the issue at our end. Please share with the following details to provide you a better solution as early as possible.

1.	Share the full Grid code example.
2.	Share the exact scenario/proper replication procedure.

**Comment by Pavithra15** [comment]
Hi @Sven65,

We have added the fix for the issue –“ Selection is not maintained when using rowselected and rowdeselected event” in our patch release (v16.4.54). So please update your packages to this version/latest version(v19.4.47) to include the fix.  Please contact us if you would require any further assistance. 

Regards,
Pavithra S
