### ISSUE TITLE
Document Editor: print content in table bug

### ISSUE THREAD

**Issue by alex-misch** [syncfusion/ej2-react-ui-components#50]
Hi. I have an issue with printing document.
I checking this demo: https://ej2.syncfusion.com/react/demos/#/material/document-editor/default
When I'm pressing to "print", content inside tables are not exported into print version.

Browser: Chrome 81.0.4044.138
OS: MacOS Catalina 10.15.4.

**Comment by harinichellappa1921** [comment]
Hi @alex-misch ,

This issue has been resolved in latest version of document editor source. 

Kindly upgrade your NPM packages to latest version to resolve the reported issue. 

https://www.npmjs.com/package/@syncfusion/ej2-react-documenteditor

Release Notes 

https://ej2.syncfusion.com/react/documentation/release-notes/18.1.53/#document-editor 

Regards, 

Harini C

**Comment by alex-misch** [comment]
thank you!
