### ISSUE TITLE
React Strict Mode - Errors thrown by the CheckBoxComponent

### ISSUE THREAD

**Issue by adrien-nc** [syncfusion/ej2-react-ui-components#53]
The @syncfusion/ej2-react-buttons (v18.1.52) CheckBoxComponent throws errors when React strict mode is enabled.

Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.
- Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: CheckBoxComponent

Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

- Move data fetching code or side effects to componentDidUpdate.
- If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: CheckBoxComponent

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of CheckBoxComponent which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

**Comment by jesusarockias** [comment]
Greetings from Syncfusion, 

Currently we do not have support to achieve your requirement “React Strict Mode is not working“ but we have logged a feature request on this and it can be tracked through our feedback portal below.

Link : https://www.syncfusion.com/feedback/15466/react-strict-mode-is-not-working

Please cast your vote to make it count. We will prioritize the features every release based on the demands.

If you have any more specification/suggestions to the feature request you can add it as a comment in the portal.

Regards,
Jesus Arockia Sankaran S

**Comment by Mydeen-SN** [comment]
Hi @adrien-nc ,

We have upgraded our components to new lifer cycle hooks and resolve the warning errors in strict mode. We recomment to use latest version of our packages to include this changes.

Regards,
Mydeen S N
