### ISSUE TITLE
ChartComponent does not resize when resizing a tile of a DashboardLayoutComponent

### ISSUE THREAD

**Issue by aleksander351** [syncfusion/ej2-react-ui-components#54]
I am testing out the React UI components with Material style.

I want to display some charts inside the tiles of a DashboardLayoutComponent.

When I resize a tile with a chart, the chart doesn't resize. If I resize the browser window, the chart resizing gets trigered.

![image](https://user-images.githubusercontent.com/7508670/84238562-84d0a180-aafb-11ea-845e-14f843fee676.png)

**Comment by Baby-Palanidurai** [comment]
Chart rendered when we resize on browser window only. If we want to refresh when on dashboard layout panel resize, we need to refresh the charts in the dashboard layout resize events,
 
Sample link: https://stackblitz.com/edit/react-yg1vub?file=index.js
  
Kindly revert us, if you have any concerns.

**Comment by aleksander351** [comment]
Ok, got it working. Thank you very much.
Not very pretty, but it's working.

**Comment by aleksander351** [comment]
> Chart rendered when we resize on browser window only. If we want to refresh when on dashboard layout panel resize, we need to refresh the charts in the dashboard layout resize events,
> 
> Sample link: https://stackblitz.com/edit/react-yg1vub?file=index.js
> 
> Kindly revert us, if you have any concerns.

`(args.element.querySelector('.e-panel-container .e-panel-content div div')).ej2_instances[0];`

Why does the selector need to be so complicated?

**Comment by aleksander351** [comment]
Also another issue, when data is updating in React, the **`chartTemplate`** component inside **`DashboardLayoutComponent`** is not updating.

    `
    <DashboardLayoutComponent
        id="01"
        cellSpacing={cellSpacing}
        columns={6}
        allowResizing={true}
        resize={(event) => onPanelResize(event)}
      >
        <PanelsDirective>
          <PanelDirective
            row={0}
            col={1}
            sizeX={3}
            sizeY={2}
            content={chartTemplate}
          />
        </PanelsDirective>
      </DashboardLayoutComponent>
    `

Maybe if we could put **`chartTemplate`** directly into a **`PanelDirective`** the chartTemplate would update.

    `
       <PanelDirective
            row={0}
            col={1}
            sizeX={3}
            sizeY={2}
            content={chartTemplate}
          >
            <ChartTemplate someProp={someProp}/>
          </PanelDirective>
    `

**Comment by aleksander351** [comment]
Another Issue: 

**resize** event is of type **ResizeArgs> | undefined**.

And inside the function it returns:
Property 'ej2_instances' does not exist on type 'Element'.
Which is HtmlElement in this case. 

See dashboard-layout.d.ts:
Interface ResizeArgs {
    element: **HTMLElement**;

    etc.
}

**Comment by SharonSanchez** [comment]
@aleksander351 
Query 1: when data is updating in React, the chartTemplate component inside DashboardLayoutComponent is not updating.

In Dashboard Layout component, you can render the required component using the content Template property. 
https://ej2.syncfusion.com/documentation/api/dashboard-layout/panel/#content

Please find the below code blocks:


<DashboardLayoutComponent id="edit_dashboard" columns={2} cellSpacing={this.cellSpacing} ref={(scope) => { this.dashboardObj = scope; }}    resize={this.onPanelResize.bind(this)} allowResizing={true} allowDragging={true}>                   <PanelsDirective>                       <PanelDirective sizeX={1} sizeY={1} row={0} col={0} content={this.lineTemplate} header="<div>Line Chart</div>"></PanelDirective>                   </PanelsDirective>                   </DashboardLayoutComponent>               lineTemplate() {           let data1 = [{ x: 'Jan', y: 46 }, { x: 'Feb', y: 27 }, { x: 'Mar', y: 26 }];           let data2 = [{ x: 'Jan', y: 37 }, { x: 'Feb', y: 23 }, { x: 'Mar', y: 18 }];           let data3 = [{ x: 'Jan', y: 38 }, { x: 'Feb', y: 17 }, { x: 'Mar', y: 26 }];           return (<div className="template">                <ChartComponent style={{ "height": "100%", "width": "100%" }} primaryXAxis={{ valueType: 'Category', interval: 1, majorGridLines: { width: 0 } }} primaryYAxis={{               majorGridLines: { width: 0 },               majorTickLines: { width: 0 }, lineStyle: { width: 0 }, labelStyle: { color: 'transparent' }           }} chartArea={{ border: { width: 0 } }} tooltip={{ enable: true }}>                           <Inject services={[ColumnSeries, Legend, Tooltip, Category, DataLabel]}/>                           <SeriesCollectionDirective>                               <SeriesDirective dataSource={data1} xName='x' yName='y' name='Jan' type='Column' marker={{ dataLabel: { visible: false } }} fill='#00bdae'>                               </SeriesDirective>                               <SeriesDirective dataSource={data2} xName='x' yName='y' name='Feb' type='Column' marker={{ dataLabel: { visible: false } }} fill='#e56691'>                               </SeriesDirective>                               <SeriesDirective dataSource={data3} xName='x' yName='y' name='Mar' type='Column' marker={{ dataLabel: { visible: false } }} fill='#357cd2'>                               </SeriesDirective>                           </SeriesCollectionDirective>                       </ChartComponent>               </div>).       }
--


Please find the below previously shared sample.

https://stackblitz.com/edit/react-yg1vub?file=index.js


Query 2: resize event is of type ResizeArgs> | undefined. And inside the function it returns:
Property 'ej2_instances' does not exist on type 'Element'.
Which is HtmlElement in this case.

Please find the ResizeArgs related details

https://ej2.syncfusion.com/react/documentation/api/dashboard-layout/panel/#content


Event argument | Type
-- | --
Event | MouseEvent \| TouchEvent
isInteracted | Boolean

Please can you provide details as to where your issue occurs and in which scenario? This will help us to proceed further.

**Comment by Thirukumanaran** [comment]
Hi @aleksander351 ,

Please feel free to contact us if you experience any further problems/issues.

Regards,
Thirukumaran M.
