### ISSUE TITLE
Improve theming capabilities of Theme Studio

### ISSUE THREAD

**Issue by aleksander351** [syncfusion/ej2-react-ui-components#56]
Right now, there is no straightforward way of switching a color scheme dynamically in an application. The Theme Studio generates a (large) file with all the CSS rules and fonts inside. This also makes the css imports from node_modules redundant.

It would be better, to include styling capabilities right into the framework, separated into components and with as little variables as needed. The color variables should be in a separate file and flexible enough to enable multiple color schemes of an application at the same time. For example to be able to switch between light and dark mode.

**Comment by jesusarockias** [comment]
@aleksander351 Sorry for the inconvenience.

We have checked your query and we want to inform you that we do not have support for directly importing styles in React framework. And, we have already planned to improve our SCSS structure that you can track using the below feedback portal link. 

Feedback: https://www.syncfusion.com/feedback/8141/provide-latest-sass-version-support-with-ej2-components

We expect that it will be available with our Volume 3, 2020 release. If you have any more specification/suggestions to the feature request you can add it as a comment in the portal.

Please get back to us if you need any further assistance on this.
