### ISSUE TITLE
Inconsistent import packages of styles

### ISSUE THREAD

**Issue by aleksander351** [syncfusion/ej2-react-ui-components#58]
Hi,

We are importing styles based on the components we are using: 

@import '../node_modules/@syncfusion/**ej2-base**/styles/material.css';
@import '../node_modules/@syncfusion/**ej2-react-navigations**/styles/material.css';
@import '../node_modules/@syncfusion/**ej2-react-grids**/styles/material.css';
@import '../node_modules/@syncfusion/**ej2-popups**/styles/material.css';

As you can see, sometimes the styles are react specific, and sometimes they are not.

Why is there no React package for every component?
Why is there no React package for base styles?

**Comment by jesusarockias** [comment]
Sorry for the inconvenience.

We would like to let you know that EJ2 React packages uses styles from dependent JavaScript packages since both have same appearance regardless of its platform.

Please get back to us if you need any further assistance on this.
