### ISSUE TITLE
ChartComponent not updating when inside PanelDirective of DashboardLayoutComponent

### ISSUE THREAD

**Issue by aleksander351** [syncfusion/ej2-react-ui-components#59]
When data is updating in React (state or context), the **`ChartComponent `** component inside **`DashboardLayoutComponent`** is not updating.

In my example, chartTemplate is a ChartComponent.

    `
    <DashboardLayoutComponent
        id="01"
        cellSpacing={cellSpacing}
        columns={6}
        allowResizing={true}
        resize={(event) => onPanelResize(event)}
      >
        <PanelsDirective>
          <PanelDirective
            row={0}
            col={1}
            sizeX={3}
            sizeY={2}
            content={chartTemplate}
          />
        </PanelsDirective>
      </DashboardLayoutComponent>
    `

Maybe if we could put **`chartTemplate`** directly into a **`PanelDirective`** the chartTemplate would update?

For example:

    `
       <PanelDirective
            row={0}
            col={1}
            sizeX={3}
            sizeY={2}
        >
            <ChartTemplate someProp={someProp}/>
        </PanelDirective>
    `

**Comment by DurgaGopalakrishnan** [comment]
Hi Alexsander,

We have validated your reported scenario with provided snippet. We were able to render the chart template inside dashboard layout using panels. We have prepared sample for your reference. 

**Code Snippet**

    <DashboardLayoutComponent id="edit_dashboard" columns={2} cellSpacing={this.cellSpacing} 
     ref={(scope) => { this.dashboardObj = scope; }}
      resizeStop={this.onPanelResize.bind(this)} allowResizing={false} allowDragging={false}>
      <PanelsDirective>
         <PanelDirective sizeX={0} sizeY={0} row={0} col={0} content={this.lineTemplate} header="<div>Line Chart</div>">
         </PanelDirective>
      </PanelsDirective>
    </DashboardLayoutComponent>

**Screenshot**

<img width="244" alt="dashboardline" src="https://user-images.githubusercontent.com/41737182/88028247-05041100-cb56-11ea-8f6a-fef2d1bc48cd.png">

**Sample**

https://stackblitz.com/edit/react-psffao

Kindly revert us, if you have any concerns.

Regards,
Durga G

**Comment by Thirukumanaran** [comment]
Hi Alexsander,

Please feel free to contact us if you experience any further problems/issues.

Regards,
Thirukumaran M.
