### ISSUE TITLE
ScheduleComponent data disappear on re-render

### ISSUE THREAD

**Issue by ennesp** [syncfusion/ej2-react-ui-components#60]
I noticed the data inside ScheduleComponent disappears on re-render when state or props are updated. More precisely it is the data inside resourceHeaderTemplate. 

I'm providing a working example where you can see or reproduce the issue: 

[https://stackblitz.com/edit/react-hr7hvq](https://stackblitz.com/edit/react-hr7hvq)

The component state will update after five seconds and you can notice the resource header data disappears.

Any solution to this?

**Comment by VengateshManiraj** [comment]
@ennesp Greetings from Syncfusion Support.

We checked the reported problem in the shared sample by you and we suggest you please enable the **delayUpdate** property to resolve this problem.

`<ScheduleComponent
                delayUpdate="true"
                ref={schedule => (this.scheduleObj = schedule)}
                cssClass="block-events"
                width="100%"
                height="650px"
                selectedDate={new Date(2018, 7, 1)}
                currentView="TimelineDay"
                resourceHeaderTemplate={this.resourceHeaderTemplate.bind(this)}
                eventSettings={{
                  dataSource: this.data
                }}
                group={{ enableCompactView: false, resources: ["Employee"] }}
              >`

You can check these changes in the below sample.

https://stackblitz.com/edit/react-hr7hvq-i3g7aj

To know more about the **delayUpdate** property, please visit the below UG site.

https://ej2.syncfusion.com/react/documentation/common/how-to/resolve-react-template-issues/

**Comment by ennesp** [comment]
> @ennesp Greetings from Syncfusion Support.
> 
> We checked the reported problem in the shared sample by you and we suggest you please enable the **delayUpdate** property to resolve this problem.
> 
> `<ScheduleComponent delayUpdate="true" ref={schedule => (this.scheduleObj = schedule)} cssClass="block-events" width="100%" height="650px" selectedDate={new Date(2018, 7, 1)} currentView="TimelineDay" resourceHeaderTemplate={this.resourceHeaderTemplate.bind(this)} eventSettings={{ dataSource: this.data }} group={{ enableCompactView: false, resources: ["Employee"] }} >`
> 
> You can check these changes in the below sample.
> 
> https://stackblitz.com/edit/react-hr7hvq-i3g7aj
> 
> To know more about the **delayUpdate** property, please visit the below UG site.
> 
> https://ej2.syncfusion.com/react/documentation/common/how-to/resolve-react-template-issues/

Thanks, it works!

**Comment by sellakumark** [comment]
@ennesp - We are happy to hear this from you. if you have any queries and revert us for further assistance.
