### ISSUE TITLE
Type error when using Schedule with quickInfoTemplate

### ISSUE THREAD

**Issue by rchavik** [syncfusion/ej2-react-ui-components#65]
The following error is found in console after switching to another route that is using codesplitting.
It also only happens after the quickInfoPopup is shown at least once.

```
Uncaught TypeError: button.ej2_instances is undefined
    destroyButtons quick-popups.js:1330
    destroy quick-popups.js:1365
    destroyPopups schedule.js:1416
    destroy schedule.js:2050
    componentWillUnmount component-base.js:227    
    unstable_runWithPriority scheduler.development.js:653    
    unstable_runWithPriority scheduler.development.js:653
    React 6
```

![image](https://user-images.githubusercontent.com/39490/90327952-a601b280-dfc2-11ea-8af5-eeef8905cef8.png)

Snippet of component causing the error:

```tsx
export const MySchedule = () => {
  const footer: string | any = (props: { [key: string]: Object }) => {
    const onViewDetail = () => {
      // show detail ...
    }

    return (<div>
      <div className="e-popup-footer">
        <button className="e-event-details e-text-ellipsis e-control e-btn e-lib e-flat e-primary" onClick={ onViewDetail } title="View Details">Details</button>
      </div>
    </div>);
  }

  return (
    <ScheduleComponent
      // if this config is commented, the error does not happen
      quickInfoTemplates={{
        footer: footer,
      }}>
      { /* .... view directives */ }
    </ScheduleComponent>
  );
}
```

**Comment by rchavik** [comment]
Following components are being used:
```
    "@syncfusion/ej2-base": "^18.2.47",
    "@syncfusion/ej2-react-calendars": "^18.2.44",
    "@syncfusion/ej2-react-charts": "^18.2.48",
    "@syncfusion/ej2-react-gantt": "^18.2.48",
    "@syncfusion/ej2-react-schedule": "^18.2.47",
```

**Comment by VengateshManiraj** [comment]
We have validated your shared code snippets at our end. And for that, we have prepared a sample using **quickInfoTemplate** property and it is working fine at our end and the sample can be viewed from the following link. 

Sample: https://stackblitz.com/edit/react-vdqrxe?file=index.js 

And for further reference, kindly refer the below UG link and Live demo sample link, 

Live demo link: https://ej2.syncfusion.com/react/demos/#/material/schedule/quick-info-template 
UG link: https://ej2.syncfusion.com/react/documentation/schedule/editor-template/#customizing-quick-popups

**Comment by rchavik** [comment]
Hi,

Thanks for looking into this, however that link is just a static page displaying the schedule component.

Please check https://github.com/rchavik/repro-issue-65 and follow the steps to reproduce the bug:
- Click on the Schedule menu
- Click on any appointment displayed so the detail popup from the footer is shown.
- Optional: Click on the `Detail` button and see the alert displaying the appointment id.
- Click on Home menu. This should crash the application resulting in a white screen.

Also viewable here: https://repro-issue-65.vercel.app/

**Comment by Balasubramanian-Sattanathan** [comment]
Dear Customer,

We have validated your shared snippets at our end. And we could able to replicate your reported problem at our end and we suspect that you have maintained the static class name for the button “e-event-details” for both the cell click and event click that could be the reason for the reported problem and we have prepared a sample and it can be viewed from the following link.

**Sample:** https://stackblitz.com/edit/react-vdqrxe-evhziv-c4rzc3?file=index.js

**Code snippet**

```
footerTemplate(props) {
    return (
      <div className="quick-info-footer">
        {props.elementType == "cell" ?
          <div><button className="e-event-details e-text-ellipsis e-control e-btn e-lib e-flat e-primary" onClick={this.buttonCellClickActions.bind(this)} title="View Details">Details</button></div>
          :
          <div><button className="e-event-edit e-text-ellipsis e-control e-btn e-lib e-flat e-primary" onClick={this.buttonEventClickActions.bind(this)} title="View Details">Details</button></div>
        }
      </div>
    );
  }
```

And for further reference, kindly refer the below UG link and live demo sample link,

**Live demo link:** https://ej2.syncfusion.com/react/demos/#/material/schedule/quick-info-template
**UG link:** https://ej2.syncfusion.com/react/documentation/schedule/editor-template/#customizing-quick-popups

Kindly try the above solution and get back to us if you need any further assistance.

Regards,
Balasubramanian S

**Comment by rchavik** [comment]
> Dear Customer,
> 
> We have validated your shared snippets at our end. And we could able to replicate your reported problem at our end and we suspect that you have maintained the static class name for the button “e-event-details” for both the cell click and event click that could be the reason for the reported problem and we have prepared a sample and it can be viewed from the following link.
> 
> **Sample:** https://stackblitz.com/edit/react-vdqrxe-evhziv-c4rzc3?file=index.js

The link seems to be invalid.

> 
> **Code snippet**
> 
> ```
> footerTemplate(props) {
>     return (
>       <div className="quick-info-footer">
>         {props.elementType == "cell" ?
>           <div><button className="e-event-details e-text-ellipsis e-control e-btn e-lib e-flat e-primary" onClick={this.buttonCellClickActions.bind(this)} title="View Details">Details</button></div>
>           :
>           <div><button className="e-event-edit e-text-ellipsis e-control e-btn e-lib e-flat e-primary" onClick={this.buttonEventClickActions.bind(this)} title="View Details">Details</button></div>
>         }
>       </div>
>     );
>   }
> ```

This avoid the crash, however the behavior is not totally correct.
- I only care to show the Details button when `props.elementType !== 'event'.
- I do not care for editing and do not want to show the edit form

I think the library should not assume that a button will exists and checks for empty instead of having leaking internal details.

**Comment by vinithadevi** [comment]
Dear Customer,

Thanks for the update. 

We have validated your shared query at our end. And we suspect that your requirement is to render the Button component using footerTemplate only for the “event” type (i.e., props.elementType === 'event' ) and for that, we have prepared a sample and it can be viewed from the following link. 
 
Sample: https://stackblitz.com/edit/react-nqose7?file=index.js  
 
Kindly check it with above sample and revert us with further details, if we have misunderstood your requirement or else if you need any further assistance on this. 

Regards,
Vinitha

**Comment by rchavik** [comment]
Hi..

Thanks again for looking into this.

Unfortunately this is still not 100%.

Pretend `buttonClickActions` is shows a modal dialog that shows my custom details. L

When I close that dialog, the Edit dialog is shown. This part is not desired.

**Comment by Hareesh22** [comment]
Dear Customer,

Thanks for the update.

We have validated your shared query “**_shows a modal dialog that with my custom event details. When I close that dialog, the Edit dialog is shown. This part is not desired._**” at our end. And we suspect that your requirement is to prevent the default Edit dialog window. And for that, we have modified our previously shared sample using popupOpen event and the sample can be viewed from the below link.

**Sample**: https://stackblitz.com/edit/react-nqose7-bv5sg7?file=index.js  

**Code snippet**;
```
  onPopupOpen(args) {
    if (args.type == "Editor" && args.target.classList.contains('e-appointment')) {
      args.cancel = true;
    }
  }
```

Kindly try the above solution and get back to us if you need any further assistance.

Regards,
Hareesh

**Comment by rchavik** [comment]
Hi,

That works! Thank you.

**Comment by rchavik** [comment]
I'm closing this. Thanks again for the help all.

However, I still think that this is unnecessarily complex workaround.  It would be better if it could be streamlined.
