### ISSUE TITLE
Maps : Updating baseLayerIndex using state variable

### ISSUE THREAD

**Issue by Shrikey26** [syncfusion/ej2-react-ui-components#68]
I have the following code 

    function App() {
    const [count, setCount] = React.useState(1);

    return (
    <div>
      <button onClick={() => setCount(count + 1)} >+</button>
      <button onClick={() => setCount(count - 1)} >-</button>
      <div>{count}</div>
      <MapsComponent height="600"  id="maps"  baseLayerIndex = {count} >
        <Inject services={[DataLabel, MapsTooltip]} />
        <LayersDirective>
          <LayerDirective shapeData={world_map} tooltipSettings={{
            visible: true,
            valuePath: 'st_nm'
          }}>
          </LayerDirective>
          <LayerDirective shapeData={countryData} tooltipSettings={{
            visible: true,
            valuePath: 'name'
          }}>
          </LayerDirective>
        </LayersDirective>
      </MapsComponent>
     </div>);
    }

I have both world_map and countryData. When I click on '+' or '-', the map goes blank. 
I dont want to use the 'ref' for updating maps. 

Is there anyway which I can achieve this using state variables

**Comment by indumathi-murali** [comment]
We are able to reproduce the reported scenario. When we change the layer of the maps using the "baseLayerIndex" property in the maps, the layer will not get appended to the map. Only when we refresh the map, the selected layer will be visible on the client-side. So it is necessary to get the reference of the Maps component and call the refresh() method when the baseLayerIndex is changed. We have created a simple sample using your code snippet and the same can be downloaded from the below link.

https://www.syncfusion.com/downloads/support/directtrac/291973/ze/MapsStateVariable-1149337635

**Comment by Shrikey26** [comment]
@indumathi-murali  : I am unable to access the link even after signing in. Anyways, I have used ref and refreshing the map for any required changes
