### ISSUE TITLE
ej2-react-grid

### ISSUE THREAD

**Issue by mohamedmohsin** [syncfusion/ej2-react-ui-components#7]
both  column freeze and virtualization in a grid , shows error 

Error in /turbo_modules/@syncfusion/ej2-grids@16.4.55/dist/ej2-grids.umd.min.js (10:460571)
Cannot read property 'blockIndexes' of undefined

**Comment by pavithra95subramaniam** [comment]
Hi @mohamedmohsin ,

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts. We have added this feature request to our database. You can now track the current status of this feature request here https://www.syncfusion.com/feedback/4950/grid-frozen-rows-and-columns-support-for-virtualization . At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. Currently we don’t have any immediate plan for implementing this feature and it will be available in any of our upcoming release.

Regards,
Pavithra S.

**Comment by Pavithra15** [comment]
Hi @mohamedmohsin,

We have provided the support for the ‘Grid frozen rows and columns support for the virtualization’ feature. So please update your packages to the latest version(v19.4.47) to use this feature. Please contact us if you would require any further assistance. 

Regards,
Pavithra S
