### ISSUE TITLE
[@syncfusion/ej2-react-grids] parcel build error

### ISSUE THREAD

**Issue by rhkdgns95** [syncfusion/ej2-react-ui-components#70]
This error continues to occur. 
The same problem occurs even if a new installation is performed after removing node_modules and package.json. 
Is there a way to resolve this error?

Help.

- **my package.json**
```json
{
  "dependencies": {
    "@syncfusion/ej2-base": "^18.2.59",
    "@syncfusion/ej2-react-grids": "^18.2.55",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4",
    "typescript": "^3.9.3"
  },
  "scripts": {
    "start": "parcel -p 3000 index.html --open"
  }
}

```

```bash
$ npm run start
```

- **console**
```bash
Error:  TypeError: Cannot redefine property: CheckBoxSelection
    at Function.defineProperty (<anonymous>)
    at react-dom.development.js:25012
    at Array.forEach (<anonymous>)
    at Object.parcelRequire.../node_modules/@syncfusion/ej2-dropdowns/src/index.js../common/index (react-dom.development.js:25012)
    at newRequire (Helmet.js:30)
    at localRequire (enum.ts:57)
    at Object.parcelRequire.../node_modules/@syncfusion/ej2-dropdowns/index.js../src/index (react-dom.development.js:25012)
    at newRequire (Helmet.js:30)
    at localRequire (enum.ts:57)
    at Object.parcelRequire.../node_modules/@syncfusion/ej2-grids/src/grid/common/excel-filter-base.js.@syncfusion/ej2-base (react-dom.development.js:25012)
```

![image](https://user-images.githubusercontent.com/46029124/93836498-f9e87100-fcbd-11ea-8884-eeda707ed488.png)

**Comment by rhkdgns95** [comment]
**Problem**

node_modules/@syncfusion/ej2-dropdowns/src/multi-select/checkbox-selection.js 



```ts
// 514 Line.
// export { CheckBoxSelection };    before
export default CheckBoxSelection;  // it`s working.
```

**Comment by mohankumar91** [comment]
Hi @rhkdgns95 ,

Sorry for the inconvenience caused.  We have checked your reported issue, we are able to reproduce it in our end. We have logged an issue report for this and we will include this fix in our upcoming patch release. You can track the status in the below feedback link.
 
Feedback Link: https://www.syncfusion.com/feedback/18340/module-injection-issue-in-parcel-builder 

Regards,
Mohan kumar R

**Comment by mohankumar91** [comment]
Hi @rhkdgns95 ,

We are glad to announce that our Essential Studio 2021 Volume 2 Main release v19.2.0.44 is rolled out and is available for download under the following link. We have provided the support [module injection issue] in this release. Please upgrade your project by using the below link.


Essential Studio 2021 Volume 2 Main Release v19.2.0.44 is available for download | Announcements Forums | Syncfusion


We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.


Regards,

Mohan kumar R
