### ISSUE TITLE
Schedule - Cell, Header Template Disappears

### ISSUE THREAD

**Issue by Kannndev** [syncfusion/ej2-react-ui-components#72]
In Schedule component whenever we click on a cell to add a new event, cell and header templates are getting removed.

https://ej2.syncfusion.com/react/demos/?_ga=2.193674221.1913756779.1603348425-1773056668.1599721928#/material/schedule/cell-template

**Comment by Satheeshkumar0195** [comment]
Hi Kannandev,
  
We have validated your reported query "GitHub: Schedule - Cell, Header Template Disappears" and we let you know that this issue has resolved in our latest package version (18.3.0.42). So we suggest you please upgrade your version to the latest to get this changes. And, we will refresh our online demo sample in our upcoming release.  

Sample: https://stackblitz.com/edit/react-tthrmf?file=index.js 
  
Kindly try the above sample and get back to us, If you need further assistance. 
  
Regards, 
Satheesh Kumar B

**Comment by Kannndev** [comment]
Working. Thanks

**Comment by jaredkove** [comment]
This seems to be reoccurring only on windows & chrome on the newer versions. We rolled back to the above mentioned version and it's all fine, so has regressed.

Our specific problem was clicking the next week / prev week buttons a random amount of times each and just those would disappear.
