### ISSUE TITLE
drop down event triggered at each click in document editor component

### ISSUE THREAD

**Issue by francoisplet** [syncfusion/ej2-react-ui-components#73]
Hi,

I'm using the React DocumentEditor component and built my own header menu using the API.

After upgrading package version to 18.3.44 (from 18.2.57), now an error appears at each click when the DocumentEditorComponent is mounted
PS: I'm not using the Dopdown button in my code

![image](https://user-images.githubusercontent.com/56536057/97697099-ce1f8e80-1aa6-11eb-800c-2104d2f70d16.png)

**Comment by francoisplet** [comment]
My bad, maybe from cache, I don't get it anymore

**Comment by harinichellappa1921** [comment]
Hi @francoisplet 

Can you please clear your nuGet and browser cache and try again. 

And let us know whether you can able to reproduce the reported issue after clearing cache.

**Comment by francoisplet** [comment]
Hi,
after clearing cache everything was ok. 
Sorry for opening this issue too quickly
