### ISSUE TITLE
Document Editor - issues with tables

### ISSUE THREAD

**Issue by andrei10k** [syncfusion/ej2-react-ui-components#77]
Steps to reproduce: 

Open a word file that contains a table. Try to resize the table inside the document editor. From left to right, right to left, width, height. Sometimes it works, sometimes not.

**Comment by gunasekarant** [comment]
Hi @andrei10k, 

We tried resizing the table both horizontal and vertical, it works as expected on our side. Kindly check below video illustration for the same.
Video link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/TableResizeIssue1911927264

Can you please share the input document containing table used on your side and video illustration of problem you are facing? This will be helpful for us to investigate the problem further and provide you the solution at the earliest. 

Please let us know if you have any other questions.

Regards,
Gunasekaran

**Comment by andrei10k** [comment]
Hey @gunasekarant seems to be resolved now with the last week's version upgrade. I tested it myself and it works
