### ISSUE TITLE
Excel file pivot table/chart not rendering

### ISSUE THREAD

**Issue by AstroProjection** [syncfusion/ej2-react-ui-components#79]
Steps to reproduce:
1. Open an excel spreadsheet which contains a pivot table/chart in a separate sheet from the data.
2. All the other sheets open up, except for the sheets that contain the chart/pivot table.

Note:
1. I added allowChart=true
Is this a known issue?

ej-react-spreadsheet Image: ( chart1 , chart3 are not shown )
![ej-react-ui-components](https://user-images.githubusercontent.com/13699537/116078650-8031bf00-a6b4-11eb-8fb0-1f927012b283.png)

LibreOffice spreadsheet viewer: (chart1, chart 3 are there )
![libreoffice](https://user-images.githubusercontent.com/13699537/116078684-8cb61780-a6b4-11eb-8a67-91fdf0efd028.png)

**Comment by Thaneegairaj7** [comment]
Hi AstroProjection, 

We are sorry for the delay.  

We have logged this as bug report and it will be available in our Volume 1 release which will be scheduled on or before 25th March ,2022.

You can also track the status of this bug by using below feedback portal link.     

Feedback Link: https://www.syncfusion.com/feedback/33176/excel-file-with-chart-not-rendering

We appreciate your patience until then.  

Regards,             
Thaneegairaj S

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. Requesting to tracking feature and bug status through feedback portal links shared above.
