### ISSUE TITLE
syncfusion/ej2-react-gantt selectedRowIndex not persisting

### ISSUE THREAD

**Issue by dnohashi** [syncfusion/ej2-react-ui-components#85]
Package: syncfusion/ej2-react-gantt
Version: 19.1.66

The selected row in the Gantt chart does not persist through re-renders. 
Consider the following scenario as an example:
1. Select a row
2. Update data by adding new entry
3. Gantt chart re-renders with updated data
4. Selected row does not persist

**Comment by MonishaSivanthilingam** [comment]
Hi dnohashi,

Greetings from Syncfusion support.

Currently, we do not have support to persist selection after data is updated in Gantt Chart. However, we can achieve this through a workaround. By making use of the [rowSelected](https://ej2.syncfusion.com/react/documentation/api/gantt/#rowselected) event and the refresh requestType in the [actionComplete](https://ej2.syncfusion.com/react/documentation/api/gantt/#actioncomplete) event, we can maintain the selection of the record. 

We have also prepared a [sample](https://stackblitz.com/edit/react-hgkazo) for your reference.

Please contact us if you require any further assistance.

Regards,
Monisha.
