### ISSUE TITLE
GridComponent: excelExport is not a function

### ISSUE THREAD

**Issue by AliBdeir** [syncfusion/ej2-react-ui-components#88]
```js
if (args.item.id === `${props.name}_excelexport`) {
    grid.current.excelExport();
}
```
And the grid has:
```jsx
allowExcelExport={true}
```

However, when I try running the above excelExport() function, I get an error;

![image](https://user-images.githubusercontent.com/30950330/125264497-955dd780-e30c-11eb-8a3c-7a607a6d083a.png)

When I debug, I can see that excelExport actually has a value of `true`, when it should have a value of a function.

**Comment by praveenkumargspr** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/PRAVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/PRAVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/PRAVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal style='margin-bottom:12.0pt'>Hi AliBdeir,<br>
<br>
Greetings from Syncfusion support.<br>
<br>
We checked your query and provided information, in that we found you are using <b>“grid.current.excelExport()”</b>
property for PDF export, but in our EJ2 Grid, we do not have this <b>“grid.current.excelExport()”</b>
property, that’s why the reported problem exists for using this improper
property in the Grid.<br>
<br>
We suggest you to use the <b>pdfExport</b> method for exporting and enable PDF
export in the grid, set the <b>allowPdfExport</b> as true as demonstrated in
the below code example, <br>
<br>
<b>Code Example:</b><o:p></o:p></p>



export default class App   extends React.Component<{}, {}> {       public   grid: Grid \| null;       public   toolbar: ToolbarItems[] = ['PdfExport'];       public   toolbarClick = (args: ClickEventArgs) => {             if (this.grid && args.item.id === 'grid_pdfexport') {                 this.grid.pdfExport();             }       }       public   render() {           this.toolbarClick = this.toolbarClick.bind(this);           return (             <div>               <GridComponent id='grid' dataSource={data} height={270}   toolbar={this.toolbar} allowPdfExport={true}                 allowPaging={true} toolbarClick={this.toolbarClick } ref={g=> this.grid = g}>                 <ColumnsDirective>                     <ColumnDirective field='OrderID' headerText='Order ID' width='120'   textAlign='Right'/>                     <ColumnDirective field='CustomerID' headerText='Customer ID'   width='150'/>                     <ColumnDirective field='Freight' width='100' format='C2'   textAlign='Right'/>                     <ColumnDirective field='OrderDate' width='140' format='yMd'   textAlign='Right'/>                     <ColumnDirective field='ShipCity' headerText='Ship City' width='150'/>                     <ColumnDirective field='ShipName' headerText='Ship Name' width='150'   visible={false}/>                 </ColumnsDirective>               <Inject services={[Toolbar, PdfExport]}/>             </GridComponent>             </div>           );       }   }
--




<p class=MsoNormal><span style='color:black'><br>
Refer the below documentation for more information,<br>
<br>
<b>Documentation:</b> <a
href="https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fej2.syncfusion.com%2Freact%2Fdocumentation%2Fgrid%2Fpdf-export%2F&amp;data=04%7C01%7Cpraveenkumar.gajendiran%40syncfusion.com%7Cd7190368cfb444a1fb1608d945e66c9a%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637617678260345296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=A7LyynDsB95r5nj%2BZNNnAWlooq9KBt20bHA4AsUNQWw%3D&amp;reserved=0">https://ej2.syncfusion.com/react/documentation/grid/pdf-export/</a><br>
<br>
Please get back to us if you need further assistance.<br>
<br>
R</span>egards,<br>
Praveenkumar G<o:p></o:p></p>


</body>

</html>
