### ISSUE TITLE
Syncfusion Data Grid - col.edit.create is not a function

### ISSUE THREAD

**Issue by dnohashi** [syncfusion/ej2-react-ui-components#90]
I am attempting to follow https://ej2.syncfusion.com/react/documentation/grid/how-to/provide-custom-data-source-and-enabling-filtering-to-drop-down-list/ to customize the data source for an edit cell's dropdown options.

However, when I provide an `edit` object with just a params property, exactly in the way defined in that documentation, I experience the following error: "col.edit.create is not a function"

Thoughts on how to resolve this? Is the documentation accurate?

**Comment by praveenkumargspr** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/PRAVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/PRAVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/PRAVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/PRAVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal style='margin-bottom:12.0pt'>Hi Dean Ohashi,<o:p></o:p></p>

<p class=MsoNormal style='margin-bottom:12.0pt'>Greetings from Syncfusion
support.<br>
<br>
<b>Query: “However, when I provide an edit object with just a params property,
exactly in the way defined in that documentation, I experience the following
error: &quot;col.edit.create is not a function&quot;”<br>
</b><br>
We checked your query, based on that we have prepared a Grid sample to provide
custom data source and enabling filtering to editor DropDownList component and
check your reported issue, but we are not able to reproduce your reported
problem at our end. Please check the below sample and screenshot for your
reference.<br>
<br>
<b>Sample:</b> <a
href="https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackblitz.com%2Fedit%2Freact-kk2ag7%3Ffile%3Dindex.js&amp;data=04%7C01%7Cpraveenkumar.gajendiran%40syncfusion.com%7Cbeca0011af7a43ad4d2e08d95ca4f3ff%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637642685800766279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=Y6mvrYt0LuF8vp0cFX%2F49KmK2Cbt5W6a2dbGlMsd3fA%3D&amp;reserved=0">https://stackblitz.com/edit/react-kk2ag7?file=index.js</a><o:p></o:p></p>

<p class=MsoNormal>Screenshot:<o:p></o:p></p>



 
--




<p class=MsoNormal><span style='color:black'><br>
</span>Please get back to us if you need further assistance.<br>
<br>
Regards,<br>
Praveenkumar G<o:p></o:p></p>


</body>

</html>

**Comment by winniexueyao** [comment]
I have the same problem and the previous answer didn't help
![Picture1](https://github.com/syncfusion/ej2-react-ui-components/assets/73384636/9f2fadab-6f03-41f7-bbbc-751dfc19fe2d)
