### ISSUE TITLE
Error on "Section break" + "Change page(section) orientation"

### ISSUE THREAD

**Issue by Yulia-Arkan** [syncfusion/ej2-react-ui-components#91]
Hi! I need users to be able to add sections with different orientation. But there is a bug.

Check your example https://ej2.syncfusion.com/react/demos/?_ga=2.246996109.889093130.1624366370-615821001.1620994270#/material/document-editor/default . There is one section, add sectionBreak 1, add sectionBreak 2, now there are 3 sections, go to previous section (section 2), change its orientation to landscape mode, add sectionBreak, try to change this section orientation from landscape to portrait mode => there is an error:
![image](https://user-images.githubusercontent.com/19281421/129316029-ddc1018a-8fb9-4301-a3b6-0af78e1db804.png)

**Comment by kurthisBanu** [comment]
Hi Yuliia,

We can reproduce the reported issue. Currently, we are validating the reported issue. We will update further details on August 18,2021.

Regards,
Kurthis Banu A.
