### ISSUE TITLE
Having two consecutive spaces in an item name for ListViewComponent breaks react when selected 

### ISSUE THREAD

**Issue by kenkit** [syncfusion/ej2-react-ui-components#96]
I have the following setup, when the callback is triggered after the user selects an item, the event does not have a data property set.
event.data  <=== is empty
but everything else including the item seems okay.

```javascript

  listTemplate(data) {
    return (
      <div className="e-list-wrapper e-list-multi-line e-list-avatar">
        <img className="e-avatar e-avatar-circle" width="50px"  src={data.image}/>
        <span className="e-list-item-header"><b>{data.text}</b></span>
      </div>
    );
}

<ListViewComponent template={this.listTemplate} cssClass='e-list-template' showHeader={false} height={200} dataSource={this.state.datasource} select={this.handleSelect.bind(this)}    /> 
```

**Comment by kenkit** [comment]
Even having a single space at the start is lethal

**Comment by SharonSanchez** [comment]
Hi kenkit,

We have checked with the reported issue in ListView. But the event data is properly returned in the select handler.

Refer to the sample.

https://stackblitz.com/edit/react-mzhbly-4dvhzk?file=index.js

Please modify the above sample to reproduce the issue so that we can serve you better.

**Comment by kenkit** [comment]
After doing some tests I think my bug was missing the fields parameter, but I still don't get how it works without it.
I'll investigate further and get rid of the workarround I implemented after adding it.
```js
      fields={this.fields}```
