### ISSUE TITLE
Community license

### ISSUE THREAD

**Issue by mspclaims** [syncfusion/ej2-react-ui-components#98]
Please fix contractiction between https://github.com/syncfusion/ej2-react-ui-components/blob/master/license and https://www.syncfusion.com/license/studio/19.3.0.43/syncfusion_essential_studio_eula.pdf which is referenced by first document.

First document states that "To be qualified for the Syncfusion Community License Program you must have a gross revenue of less than one (1) million U.S. dollars ($1,000,000.00 USD) per year and have less than five (5) developers in your organization, and agree to be bound by Syncfusion’s terms and conditions." but second states 
"4.2.l.10 Community Licenses never include access to source code editions of the Licensed Product. "\

This project is a source code by its nature, thus either it is cannot be covered by Community License, or the clase 4.3.I should be amended to exclude Node/JavaScript products and explicitely worded to the Products that are distributed in binary form.

**Comment by gsumankumar** [comment]
Hi @mspclaims ,

Thanks for contacting Syncfusion Support.

There is a nuance here.  A source license would always guarantee that you had readable source code. The community license would not grant rights to the source while a true source license would grant this. Thus for this reason the community license would not guarantee source code access. This is independent of the fact that  even though the Java scripts are currently available in readable source, this may not always be the case in the future. We could use minification to change that in the future and compress the JavaScript controls.

Regards,
SumanKumar G
