### ISSUE TITLE
Spreadsheet - is opening XLS files in browser without server/API support on the roadmap

### ISSUE THREAD

**Issue by mpkelly** [syncfusion/ej2-react-ui-components#99]
Hi, 

This might not be the best place to ask but hope it is an easy one - as the titles say, the company I work for believes locally opening XLS files might be on your roadmap. Can you confirm this?

Thanks
Mike

**Comment by Thaneegairaj7** [comment]
Hi Mike,

Thanks for contacting Syncfusion support.

We have checked your reported requirement “import XLS file without using API/Server in spreadsheet”. And we would like to let you know that currently we are not having this support in our Spreadsheet. However, we have considered this as a feature, and it will be available in any of our upcoming releases. You can track the status in the below feedback link.

Link: [https://www.syncfusion.com/feedback/30318/need-to-import-xls-file-without-using-api-server-in-spreadsheet ](https://www.syncfusion.com/feedback/30318/need-to-import-xls-file-without-using-api-server-in-spreadsheet )

Please upvote this feature to make this our priority. While this feature itself is important we will prioritize the features every release, based on the user demands. 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal.

Regards,
Thaneegairaj S

**Comment by mpkelly** [comment]
Thanks @Thaneegairaj7. I will upvote the feature.
